### ISSUE TITLE
Crash when a nemesis is killed in SMP.

### ISSUE THREAD

**Issue by bdevo1896** [ToroCraft/NemesisSystem#85]
I have 2 problems for the 1.12 version:
 
1) My game crashes when a nemesis is killed in multiplayer.
 
2) I can't use any of the commands for the nemesis mod. When I try to bring it up in the 'help' command all you get is:  "commands.nemesis_system.usage"
 
I really like this mod and would love to find out how to fix this problem!
 
Here is the error when a nemesis is killed:
`---- Minecraft Crash Report ---- WARNING: coremods are present: LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar) BlurPlugin (Blur-1.0.4-14.jar) SHLoadingPlugin (ScalingHealth-1.12-1.3.2-77.jar) Extra Alchemy ASM (extraalchemy-0.3.6-release.jar) CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar) MovingWorldCore (movingworld-1.12-6.342-full.jar) Contact their authors BEFORE contacting forge // Uh... Did I do that? Time: 11/22/17 12:46 AM Description: Ticking entity java.lang.NoSuchMethodError: net.minecraft.entity.item.EntityItem.func_70016_h(DDD)V at net.torocraft.nemesissystem.handlers.UpdateHandler.dropItemsInHands(UpdateHandler.java:95) at net.torocraft.nemesissystem.handlers.UpdateHandler.flee(UpdateHandler.java:79) at net.torocraft.nemesissystem.handlers.UpdateHandler.handleBodyGuardUpdate(UpdateHandler.java:55) at net.torocraft.nemesissystem.handlers.UpdateHandler.livingUpdate(UpdateHandler.java:42) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_298_UpdateHandler_livingUpdate_LivingUpdateEvent.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:554) at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2083) at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50) at net.minecraft.world.World.func_72866_a(World.java:1986) at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831) at net.minecraft.world.World.func_72870_g(World.java:1948) at net.minecraft.world.World.func_72939_s(World.java:1755) at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:764) at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) at java.lang.Thread.run(Unknown Source) A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Server thread Stacktrace: at net.torocraft.nemesissystem.handlers.UpdateHandler.dropItemsInHands(UpdateHandler.java:95) at net.torocraft.nemesissystem.handlers.UpdateHandler.flee(UpdateHandler.java:79) at net.torocraft.nemesissystem.handlers.UpdateHandler.handleBodyGuardUpdate(UpdateHandler.java:55) at net.torocraft.nemesissystem.handlers.UpdateHandler.livingUpdate(UpdateHandler.java:42) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_298_UpdateHandler_livingUpdate_LivingUpdateEvent.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:554) at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2083) at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50) at net.minecraft.world.World.func_72866_a(World.java:1986) at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831) at net.minecraft.world.World.func_72870_g(World.java:1948) -- Entity being ticked -- Details: Entity Type: minecraft:zombie (net.minecraft.entity.monster.EntityZombie) Entity ID: 10916 Entity Name: Zombie Entity's Exact location: 534.47, 68.00, 819.42 Entity's Block location: World: (534,68,819), Chunk: (at 6,4,3 in 33,51; contains blocks 528,0,816 to 543,255,831), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023) Entity's Momentum: 0.00, -0.08, -0.06 Entity's Passengers: [] Entity's Vehicle: ~~ERROR~~ NullPointerException: null Stacktrace: at net.minecraft.world.World.func_72939_s(World.java:1755) at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) -- Affected level -- Details: Level name: world All players: 1 total; [EntityPlayerMP['NicoCanPlay2'/397, l='world', x=544.95, y=65.66, z=811.57]] Chunk stats: ServerChunkCache: 808 Drop: 0 Level seed: -1329860336 Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true Level generator options: Level spawn location: World: (68,64,252), Chunk: (at 4,4,12 in 4,15; contains blocks 64,0,240 to 79,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) Level time: 1163360 game time, 37075 day time Level dimension: 0 Level storage version: 0x04ABD - Anvil Level weather: Rain time: 11035 (now: true), thunder time: 46039 (now: false) Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false Stacktrace: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:764) at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) at java.lang.Thread.run(Unknown Source) -- System Details -- Details: Minecraft Version: 1.12.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_151, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 1847120344 bytes (1761 MB) / 2787639296 bytes (2658 MB) up to 2863661056 bytes (2731 MB) JVM Flags: 2 total; -Xms2G -Xmx3G IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104 FML: MCP 9.42 Powered by Forge 14.23.0.2546 45 mods loaded, 45 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored | State | ID | Version | Source | Signature | |:--------- |:-------------------------------------------- |:-------------- |:--------------------------------------------- |:---------------------------------------- | | UCHIJAAAA | minecraft | 1.12.2 | minecraft.jar | None | | UCHIJAAAA | mcp | 9.42 | minecraft.jar | None | | UCHIJAAAA | FML | 8.0.99.99 | forge-1.12.2-14.23.0.2546-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | | UCHIJAAAA | forge | 14.23.0.2546 | forge-1.12.2-14.23.0.2546-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | | UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod | | minecraft.jar | None | | UCHIJAAAA | movillages | 1.5.4 | [1.12]MoVillages-1.5.4.jar | None | | UCHIJAAAA | betterquesting | 2.5.236 | BetterQuesting-2.5.236.jar | None | | UCHIJAAAA | biomesoplenty | 7.0.1.2302 | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar | None | | UCHIJAAAA | bloodmoon | 1.5.2 | Bloodmoon-MC1.12.2-1.5.2.jar | d72e0dd57935b3e9476212aea0c0df352dd76291 | | UCHIJAAAA | chameleon | 1.12-4.1.3 | Chameleon-1.12-4.1.3.jar | None | | UCHIJAAAA | chesttransporter | 2.8.7 | ChestTransporter-1.12-2.8.7.jar | None | | UCHIJAAAA | coralreef | 2.0 | CoralReef-2.2-1.12.2.jar | None | | UCHIJAAAA | extendedrenderer | v1.0 | coroutil-1.12.1-1.1.22.jar | None | | UCHIJAAAA | coroutil | 1.12.1-1.1.20 | coroutil-1.12.1-1.1.22.jar | None | | UCHIJAAAA | configmod | v1.0 | coroutil-1.12.1-1.1.22.jar | None | | UCHIJAAAA | customizeddungeonloot | 1.0.1 | Customized Dungeon Loot (v.1.0.1).jar | None | | UCHIJAAAA | cxlibrary | 1.6.1 | cxlibrary-1.12.1-1.6.1.jar | None | | UCHIJAAAA | movingworld | 1.12-6.342 | movingworld-1.12-6.342-full.jar | None | | UCHIJAAAA | davincisvessels | @DVESSELSVER@ | davincisvessels-1.12-6.340-full.jar | None | | UCHIJAAAA | extraalchemy | 0.3.6-release | extraalchemy-0.3.6-release.jar | None | | UCHIJAAAA | hopperducts | 1.5 | hopperducts-mc1.12-1.5.jar | None | | UCHIJAAAA | infernalmobs | 1.7.3 | InfernalMobs-1.12.jar | None | | UCHIJAAAA | inventorypets | 1.4.9.9a | inventorypets-1.12-1.4.9.9a.jar | None | | UCHIJAAAA | journeymap | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar | None | | UCHIJAAAA | limelib | 1.7.9 | limelib-1.12.2-1.7.9.jar | None | | UCHIJAAAA | magicalmap | 2.2.1 | Magical Map-1.12-2.2.1.jar | None | | UCHIJAAAA | mercurius_updater | 1.0 | MercuriusUpdater-1.12.2.jar | None | | UCHIJAAAA | mobtotems | 1.12.1-0.3.0 | mobtotems-1.12.1-0.3.0.jar | None | | UCHIJAAAA | morefurnaces | 1.10.3 | MoreFurnaces-1.12.2-1.10.3.jar | None | | UCHIJAAAA | torotraits | 1.12-1 | torotraits-1.12-1.jar | None | | UCHIJAAAA | nemesissystem | 1.12.1-2 | nemesissystem-1.12.1-2.jar | None | | UCHIJAAAA | reforged | 0.7.5 | Reforged-0.7.5-1.12+.jar | None | | UCHIJAAAA | roguelike | 1.8.0 | RoguelikeDungeons-1.12.2-1.8.0.jar | None | | UCHIJAAAA | roots | 0.103 | roots-2-0.103.jar | None | | UCHIJAAAA | roughmobs | 1.0 | roughMobs1.0.13-1.12.1.jar | None | | UCHIJAAAA | ruins | 16.9 | Ruins-1.12.jar | None | | UCHIJAAAA | silentlib | 2.2.12 | SilentLib-1.12-2.2.12-93.jar | None | | UCHIJAAAA | scalinghealth | 1.3.2 | ScalingHealth-1.12-1.3.2-77.jar | None | | UCHIJAAAA | spartanshields | 1.3a | SpartanShields-1.12-1.3a.jar | None | | UCHIJAAAA | bq_standard | 2.4.134 | StandardExpansion-2.4.134.jar | None | | UCHIJAAAA | storagedrawers | 1.12-5.2.5 | StorageDrawers-1.12.1-5.3.3.jar | None | | UCHIJAAAA | twilightforest | 3.3.202 | twilightforest-1.12.2-3.3.202-universal.jar | None | | UCHIJAAAA | waystones | 4.0.17 | Waystones_1.12.1-4.0.17.jar | None | | UCHIJAAAA | wopper | 1.12-r5 | Wopper-1.12-r5.jar | None | | UCHIJAAAA | zombieawareness | 1.12.1-1.11.10 | zombieawareness-1.12.1-1.11.10.jar | None | Loaded coremods (and transformers): LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar) lumien.bloodmoon.asm.ClassTransformer BlurPlugin (Blur-1.0.4-14.jar) com.tterrag.blur.BlurTransformer SHLoadingPlugin (ScalingHealth-1.12-1.3.2-77.jar) net.silentchaos512.scalinghealth.asm.SHClassTransformer Extra Alchemy ASM (extraalchemy-0.3.6-release.jar) zabi.minecraft.extraalchemy.asm.PotionTransformer CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar) cubex2.cxlibrary.CoreModTransformer MovingWorldCore (movingworld-1.12-6.342-full.jar) Profiler Position: N/A (disabled) Player Count: 1 / 20; [EntityPlayerMP['NicoCanPlay2'/397, l='world', x=544.95, y=65.66, z=811.57]] Is Modded: Definitely; Server brand changed to 'fml,forge' Type: Dedicated Server (map_server.txt)`

**Comment by kainoa25** [comment]
Has this issue been fixed? I neeeeeeeeeeed this mod in my pack

**Comment by BLAMM67** [comment]
I have the same issue. This occurred just last night on a SMP server.
[https://pastebin.com/X723mtRm](https://pastebin.com/X723mtRm)
There hasn't been much activity on this mod lately. Can we expect any updates?

**Comment by LemADEC** [comment]
Issue is still live. The mod uses Entity.setVelocity() on server side while that method is client side only, instead the motion properties should be directly modified.
